version: '3'

services:
    app:
        build:
            context: .
            dockerfile: app.docker
        ports:
            - "8000:8000"
        deploy:
            resources:
                limits:
                    memory: 1G
